# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create env file for api
        run: |
          touch ./api/.env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> ./api/.env
          echo DB_PASS=${{ secrets.DB_PASS }} >> ./api/.env
          echo DB_HOST=${{ secrets.DB_HOST }} >> ./api/.env
          echo DB_DBNAME=${{ secrets.DB_DBNAME }} >> ./api/.env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> ./api/.env
          echo ADMIN_KEY=${{ secrets.ADMIN_KEY }} >> ./api/.env
          cat ./api/.env

      - name: Create env file for front
        run: |
          touch ./front/.env
          echo REACT_APP_PROXY_API=${{ secrets.REACT_APP_PROXY_API }} >> ./front/.env
          cat ./front/.env

      - name: "Login to Heroku"
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true

      - name: "Login to registry"
        run: "heroku container:login"


      - name: Release API.
        uses: gonuit/heroku-docker-deploy@v1.3.2 # 
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_API }}
          dockerfile_directory: ./api
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web

      - name: "Memory fix"
        run: "heroku config:set NODE_OPTIONS=\"--max_old_space_size=2560\" -a ebooks-front"

      - name: Release Front-End.
        uses: gonuit/heroku-docker-deploy@v1.3.2 # 
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_FRONT }}
          dockerfile_directory: ./front
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
          
   
